title: Sidney San Martín
description: I’m Sidney San Martín, a programmer in NYC who likes coroutines, closures and idempotence. I’ve worked for DeepTech, OkCupid, and Keybase and attended The Recurse Center in 2012.
include: [".well-known"]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "blog"
      type: "posts"
    values:
      layout: "post"
