title: Sidney San Martín
include: [".well-known"]
excerpt_separator: ""
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "blog"
      type: "posts"
    values:
      layout: "post"
